import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/lib/hooks/useAOS";
import { ThemeProvider } from "@/components/theme-provider";
import GridSmallBackground from "@/components/gridsmall-background";
import { TracingBeam } from "@/components/tracing-beam";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[inter.className, 'antialiased bg-gray-50 dark:bg-black min-h-screen'].join(' ')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange >
          <GridSmallBackground>
            <TracingBeam>
              {children}

            </TracingBeam>

          </GridSmallBackground>

        </ThemeProvider>
        <AOSInit />
      </body>
    </html>
  );
}
